from odoo import api, models


class AccountTax(models.Model):
    _inherit = "account.tax"

    @api.model
    def _prepare_base_line_grouping_key(self, base_line):
        # Since Odoo 17.0 the tax lines of an entry are generated by
        # _prepare_tax_lines(), which merges them using this grouping key.
        # Add the supported invoice and tax support to the key to keep one
        # tax line per invoice/tax support inside a withholding document,
        # like it was done by overriding _compute_tax_key()/_compute_all_tax()
        # in previous versions.
        grouping_key = super()._prepare_base_line_grouping_key(base_line)
        record = base_line.get("record")
        if (
            record is not None
            and getattr(record, "_name", None) == "account.move.line"
            and record.l10n_ec_invoice_withhold_id
        ):
            grouping_key["l10n_ec_invoice_withhold_id"] = (
                record.l10n_ec_invoice_withhold_id.id
            )
            grouping_key["l10n_ec_tax_support"] = record._get_l10n_ec_tax_support()
        return grouping_key
